name: CI para Pull Requests en .NET 8

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Compilar y probar API .NET 8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Instalar .NET Core SDK 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Compilar proyecto
        run: dotnet build --no-restore --configuration Release

      - name: Ejecutar pruebas
        run: dotnet test --no-build --verbosity normal
